adminpanel/urls.py
from django.urls import path
from . import views
from .view import blog, company, mesaj, slider , sss ,  footerimage, home_3, pages

app_name = 'adminpanel'

urlpatterns = [
    path('', views.index, name="index"),

    path('update-company-image/', company.update_company_image, name="update-company-image"),
    path('update-company-info/', company.update_company_info, name="update-company-info"),

    path('delete-mesaj/<int:pk>/', mesaj.delete_mesaj, name="delete-mesaj"),
    path('list-mesaj/', mesaj.list_mesaj, name="list-mesaj"),
    path('message-detail/<int:pk>/', mesaj.detail_mesaj, name="detail-mesaj"),
    path('add-mesaj/', mesaj.add_mesaj, name="add-mesaj"),
    path('update-sayfalar/', pages.update_sayfalar, name="update-sayfalar"),


    path('delete-sss/<int:pk>/', sss.delete_sss, name="delete-sss"),
    path('list-sss/', sss.list_sss, name="list-sss"),
    path('sss-detail/<int:pk>/', sss.detail_sss, name="detail-sss"),
    path('add-sss/', sss.add_sss, name="add-sss"),



    path('add-slider-images/', slider.add_slider_images, name="add-slider-images"),

    path('add-slider/', slider.add_slider, name="add-slider"),
    path('update-slider/<int:pk>/', slider.update_slider, name="update-slider"),
    path('detail-slider/<int:pk>/', slider.detail_slider, name="detail-slider"),
    path('delete-slider/<int:pk>/', slider.delete_slider, name="delete-slider"),
    path('list-slider/', slider.list_slider, name="list-slider"),
    path('update-slider-image/<int:pk>/', slider.update_slider_image, name="update-slider-image"),



    path('add-footer-images/', footerimage.add_footer_images, name="add-footer-images"),

    path('add-footer/', footerimage.add_footer, name="add-footer"),
    path('update-footer/<int:pk>/', footerimage.update_footer, name="update-footer"),
    path('detail-footer/<int:pk>/', footerimage.detail_footer, name="detail-footer"),
    path('delete-footer/<int:pk>/', footerimage.delete_footer, name="delete-footer"),
    path('list-footer/', footerimage.list_footer, name="list-footer"),
    path('update-footer-image/<int:pk>/', footerimage.update_footer_image, name="update-footer-image"),


    path('add-home-3/', home_3.add_home_3, name="add-home-3"),
    path('update-home-3/<int:pk>/', home_3.update_home_3, name="update-home-3"),
    path('detail-home-3/<int:pk>/', home_3.detail_home_3, name="detail-home-3"),
    path('delete-home-3/<int:pk>/', home_3.delete_home_3, name="delete-home-3"),
    path('list-home-3/', home_3.list_home_3, name="list-home-3"),
    path('update-home-3-image/<int:pk>/', home_3.update_home_3_image, name="update-home-3-image"),



    path('add-blog/', blog.add_blog, name="add-blog"),
    path('update-blog/<int:pk>/', blog.update_blog, name="update-blog"),
    path('detail-blog/<int:pk>/', blog.detail_blog, name="detail-blog"),
    path('delete-blog/<int:pk>/', blog.delete_blog, name="delete-blog"),
    path('list-blog/', blog.list_blog, name="list-blog"),
    path('update-blog-image/<int:pk>/', blog.update_blog_image, name="update-blog-image"),

]

category/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'category'

urlpatterns = [

    path('add-list-category/', views.add_list_category, name="add-list-category"),
    path('delete-category/<int:pk>/', views.delete_category, name="delete-category"),
    path('update-category/<int:pk>/', views.update_category, name="update-category"),

    path('add-list-subcategory/', views.add_list_subcategory, name="add-list-subcategory"),
    path('delete-subcategory/<int:pk>/', views.delete_sub_category, name="delete-subcategory"),
    path('update-subcategory/<int:pk>/', views.update_sub_category, name="update-subcategory"),

    path('add-list-subcategory2/', views.add_list_subcategory2, name="add-list-subcategory2"),
    path('delete-subcategory2/<int:pk>/', views.delete_sub_category2, name="delete-subcategory2"),
    path('update-subcategory2/<int:pk>/', views.update_sub_category2, name="update-subcategory2"),


    
]

order/urls.py
from django.urls import path
from .views import orders, siparis

app_name = 'order'

urlpatterns = [
    path('addtocart/<int:pk>/', orders.add_to_cart, name='addtocart'),
    path('delete-cartproduct/<int:pk>/', orders.delete_cart_product, name='delete-cartproduct'),
    path('updatecart/<int:pk>/', orders.update_cart, name='update-cart'),
    
    # path('odeme/', orders.orderproduct, name='checkout'),
    # path('sepet/', orders.cart_view, name="cart"),
    # path('stripe-odeme/', orders.stripe_view, name="stripe-odeme"),


    path('siparis-duzenle/<int:pk>/', siparis.siparis_duzenle_view, name="siparis-duzenle"),
    path('siparis-listele/', siparis.siparis_listele_view, name="siparis-listele"),
    path('siparis-sil/<int:pk>/', siparis.siparis_sil_view, name="siparis-sil"),
    
]

yagdukkanim/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('website.urls','website'),namespace='website')),
    path('adminpanel/', include(('adminpanel.urls','adminpanel'),namespace='adminpanel')),
    path('hesap/', include(('accounts.urls','accounts'), namespace='accounts')),
    path('satis/', include(('order.urls','order'), namespace='order')),
    path('kategori/', include(('category.urls','category'), namespace='category')),
    path('urun/', include(('product.urls','product'), namespace='product')),
    path('musteri/', include(('client.urls','client'), namespace='client')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.shortcuts import reverse
from unidecode import unidecode

class Category(models.Model):
    category_name = models.CharField(max_length=50)
    slug = models.SlugField(null=True, unique=True, editable=False)
    top_category = models.CharField(max_length=70, null=True, blank=True)

    def __str__(self):
        return self.category_name

    class Meta:
        verbose_name_plural = "Kategori"

    def get_sub_category(self):
        return self.sub_category.all().order_by('sub_category_name')
    
    def get_unique_slug(self):
        sayi=0
        slug = slugify(unidecode(self.category_name))
        new_slug=slug
        while Category.objects.filter(slug=new_slug).exists():
            sayi+=1
            new_slug="%s-%s"%(slug,sayi)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            category_name = self.get_unique_slug()
            self.slug = slugify(unidecode(category_name))
        else:
            category=Category.objects.get(slug=self.slug)
            if category.category_name != self.category_name:
                self.slug=self.get_unique_slug()
        super(Category,self).save()


class SubCategory(models.Model):
    sub_category_name = models.CharField(max_length=50)
    category = models.ForeignKey('Category', related_name='sub_category' ,on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(null=True, unique=True, editable=False)
    top_category = models.CharField(max_length=70, null=True, blank=True)

    def __str__(self):
        return self.sub_category_name
    class Meta:
        verbose_name_plural = "Alt Kategori"

    def get_sub_category2(self):
        return self.sub_category2.all().order_by('sub_category2_name')

    def get_unique_slug(self):
        sayi=0
        slug = slugify(unidecode(self.sub_category_name))
        new_slug=slug
        while SubCategory.objects.filter(slug=new_slug).exists():
            sayi+=1
            new_slug="%s-%s"%(slug,sayi)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            sub_category_name = self.get_unique_slug()
            self.slug = slugify(unidecode(sub_category_name))
        else:
            sub_category=SubCategory.objects.get(slug=self.slug)
            if sub_category.sub_category_name != self.sub_category_name:
                self.slug=self.get_unique_slug()
        super(SubCategory,self).save()


class SubCategory2(models.Model):
    sub_category2_name = models.CharField(max_length=50)
    sub_category = models.ForeignKey('SubCategory', related_name='sub_category2' ,on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(null=True, unique=True, editable=False)
    top_category = models.CharField(max_length=70, null=True, blank=True)

    def __str__(self):
        return self.sub_category2_name
    class Meta:
        verbose_name_plural = "Altının Altı Kategori"

    def get_unique_slug(self):
        sayi=0
        slug = slugify(unidecode(self.sub_category2_name))
        new_slug=slug
        while SubCategory2.objects.filter(slug=new_slug).exists():
            sayi+=1
            new_slug="%s-%s"%(slug,sayi)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            sub_category2_name = self.get_unique_slug()
            self.slug = slugify(unidecode(sub_category2_name))
        else:
            sub_category2=SubCategory2.objects.get(slug=self.slug)
            if sub_category2.sub_category2_name != self.sub_category2_name:
                self.slug=self.get_unique_slug()
        super(SubCategory2,self).save()



class Size(models.Model):
    size_name = models.CharField(max_length=50)
    slug = models.SlugField(null=True, unique=True, editable=False)

    def __str__(self):
        return self.size_name
    
    class Meta:
        verbose_name_plural = "Size"

    def get_unique_slug(self):
        sayi=0
        slug = slugify(unidecode(self.size_name))
        new_slug=slug
        while Size.objects.filter(slug=new_slug).exists():
            sayi+=1
            new_slug="%s-%s"%(slug,sayi)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            size_name = self.get_unique_slug()
            self.slug = slugify(unidecode(size_name))
        else:
            size=Size.objects.get(slug=self.slug)
            if size.size_name != self.size_name:
                self.slug=self.get_unique_slug()
        super(Size,self).save()


class Color(models.Model):
    color_name = models.CharField(max_length=50)
    slug = models.SlugField(null=True, unique=True, editable=False)

    def __str__(self):
        return self.color_name
    

    def get_unique_slug(self):
        sayi=0
        slug = slugify(unidecode(self.color_name))
        new_slug=slug
        while Color.objects.filter(slug=new_slug).exists():
            sayi+=1
            new_slug="%s-%s"%(slug,sayi)
        slug = new_slug
        return slug

    def save(self, *args, **kwargs):
        if self.id is None:
            color_name = self.get_unique_slug()
            self.slug = slugify(unidecode(color_name))
        else:
            size=Color.objects.get(slug=self.slug)
            if size.color_name != self.color_name:
                self.slug=self.get_unique_slug()
        super(Color,self).save()

    class Meta:
        verbose_name_plural = "Color"

category/forms.py
from django import forms
from .models import Category, SubCategory, SubCategory2

TOP_CHOICES = [
    ('Normal', 'Normal'),
    ('Top', 'Top'),
]


class AddCategoryForm(forms.ModelForm):
    category_name = forms.CharField(max_length=80, widget=forms.TextInput(attrs={'rows':5,'class': 'form-control', 'placeholder': 'Kategori Adı'}))
    top_category = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices = TOP_CHOICES,
        required=False,
    )

    class Meta:
        model = Category
        fields = ['category_name','top_category']

class AddSubCategoryForm(forms.ModelForm):
    sub_category_name = forms.CharField(max_length=80, widget=forms.TextInput(attrs={'rows':5,'class': 'form-control', 'placeholder': 'Alt Kategori Adı'}))
    top_category = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices = TOP_CHOICES,
        required=False,
    )

    class Meta:
        model = SubCategory
        fields = ['sub_category_name','top_category']

class AddSubCategory2Form(forms.ModelForm):
    sub_category2_name = forms.CharField(max_length=80, widget=forms.TextInput(attrs={'rows':5,'class': 'form-control', 'placeholder': '2. Alt Kategori'}))
    top_category = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices = TOP_CHOICES,
        required=False,
    )

    class Meta:
        model = SubCategory2
        fields = ['sub_category2_name','top_category']

adminpanel/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from accounts.views import get_auth
from .models import  Mesajlar
from django.contrib.auth import authenticate
from django.contrib.auth import update_session_auth_hash


def index(request):
    """
    flag, gidilecek_sayfa = get_auth(request)
    if flag:
        return redirect(gidilecek_sayfa)
    """

    mesajlar =Mesajlar.objects.all()



    context = { 'mesajlar':mesajlar }
    return render(request,'adminpanel/index/index.html', context)

product/views/category.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from category.models import Category, SubCategory, SubCategory2


def load_ending(request):

    category_pk = request.GET.get('category_pk')
    category = get_object_or_404(Category, pk = category_pk)

    sub_categories = SubCategory.objects.filter(category=category)
    print('****************')
    print(sub_categories)
    
    return render(request, 'adminpanel/product/load_ending.html', context={'sub_categories': sub_categories})

def load_categories(request):
    sub_category_pk = request.GET.get('sub_category_pk')
    sub_category = get_object_or_404(SubCategory, pk = sub_category_pk)

    sub_categories_2 = SubCategory2.objects.filter(sub_category=sub_category)

    return render(request, 'adminpanel/product/load_categories.html', context={'sub_categories_2': sub_categories_2})

templates/adminpanel/category/add_list_category.html
{% load static %}
{% include 'adminpanel/index/header.html' %}

<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/form_layouts.js' %}"></script>

<script src="{% static 'admin/js/plugins/media/fancybox.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/tables/datatables/datatables.min.js' %}"></script>

<script src="{% static 'admin/js/demo_pages/special/gallery_deneme.js' %}"></script>


{% include 'adminpanel/index/lefttopbar-ust.html' %}
{% include 'adminpanel/index/page-header.html' %}

<!-- Content area -->
<div class="content">

  {% if messages %}
  {% for message in messages %}
    {% ifequal message.tags 'error' %}
    <div class="alert alert-danger" role="alert">
      {{ message }}
    </div>
    {% else %}
    <div class="alert alert-{{ message.tags }}" role="alert">
      {{ message }}
    </div>
    {% endifequal %}

  {% endfor %}
  {% endif %}

      <div class="card">
        <div class="card-header header-elements-inline">
          <h5 class="card-title">Kategori Ekle/Listele</h5>
          <div class="header-elements">
            <div class="list-icons">
              <a class="list-icons-item" data-action="collapse"></a>
            </div>
          </div>
        </div>

        <div class="card-body">
          <form action="{% url 'category:add-list-category' %}" method="POST">
            {% csrf_token %}
                  <div class="form-group">
                    <label>Kategori :</label>
                    {{ form.category_name }}
                  </div>
                  <div class="form-group">
                    <label>TOP :</label>
                    {{ form.top_category }}
                  </div>
            <div class="text-right">
              <button type="submit" class="btn btn-primary"> Ekle <i class="icon-paperplane ml-2"></i></button>
            </div>
          </form>
        </div>
      </div>

    <div class="card">
    <div class="card-header bg-white header-elements-inline">
      <h4 class="card-title">Kategori</h4>
    </div>

    <table class="table table-striped media-library">
      <thead>
        <tr>
          <th><input type="checkbox" class="form-input-styled"></th>

          <th>Kategori</th>
          <th class="text-center">İşlem</th>
        </tr>
      </thead>
      <tbody>

        {% for c in categories %}

        <tr>
          <td><input type="checkbox" class="form-input-styled"></td>

          <td>
            <ul class="list-unstyled mb-0">
              <li><span class="font-weight-semibold">{{ c.category_name }}</span></li>
            </ul>
          </td>
          <td class="text-center">
            <div class="list-icons">
              <div class="list-icons-item dropdown">
                <a href="gallery_library.html#" class="list-icons-item caret-0 dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-menu9"></i>
                </a>

                <div class="dropdown-menu dropdown-menu-right">
                  <a href="{% url 'category:update-category' c.pk %}" class="dropdown-item"><i class="icon-pencil7"></i> Düzenle</a>
                  <div class="dropdown-divider"></div>
                  <a href="{% url 'category:delete-category' c.pk %}" class="dropdown-item"><i class="icon-bin"></i> Sil </a>
                </div>
              </div>
            </div>
          </td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>

</div>
<!-- /content area -->


{% include 'adminpanel/index/footer.html' %}

templates/adminpanel/category/add_list_sub_category.html
{% load static %}
{% include 'adminpanel/index/header.html' %}

<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/form_layouts.js' %}"></script>

<script src="{% static 'admin/js/plugins/media/fancybox.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/tables/datatables/datatables.min.js' %}"></script>

<script src="{% static 'admin/js/demo_pages/special/gallery_deneme.js' %}"></script>


{% include 'adminpanel/index/lefttopbar-ust.html' %}
{% include 'adminpanel/index/page-header.html' %}

<!-- Content area -->
<div class="content">

  {% if messages %}
  {% for message in messages %}
    {% ifequal message.tags 'error' %}
    <div class="alert alert-danger" role="alert">
      {{ message }}
    </div>
    {% else %}
    <div class="alert alert-{{ message.tags }}" role="alert">
      {{ message }}
    </div>
    {% endifequal %}

  {% endfor %}
  {% endif %}

      <div class="card">
        <div class="card-header header-elements-inline">
          <h5 class="card-title">Kategorie Hinzufügen/Liste</h5>
          <div class="header-elements">
            <div class="list-icons">
              <a class="list-icons-item" data-action="collapse"></a>
            </div>
          </div>
        </div>

        <div class="card-body">
          <form action="{% url 'category:add-list-subcategory' %}" method="POST">
            {% csrf_token %}
              <div class="form-group">
                <label>Kategorie :</label>
                {{ form.sub_category_name }}
              </div>
                  <div class="form-group">
                    <label>TOP :</label>
                    {{ form.top_category }}
                  </div>
              <div class="form-group">
                <label>Kategorie:</label>
                <select name="category_pk" id="id_category" data-placeholder="Kategori Seçiniz" class="form-control" >
                  <option value="">------</option>
                  {% for c in categories %}
                    <option value="{{c.pk}}">{{ c.category_name }}</option>
                  {% endfor %}
                </select>
              </div>



              <div class="text-right">
                <button type="submit" class="btn btn-primary"> Hinzufügen <i class="icon-paperplane ml-2"></i></button>
              </div>
          </form>
        </div>
      </div>

    <div class="card">
    <div class="card-header bg-white header-elements-inline">
      <h4 class="card-title">Kategorie</h4>
    </div>

    <table class="table table-striped media-library">
      <thead>
        <tr>
          <th><input type="checkbox" class="form-input-styled"></th>

          <th>Kategorie</th>
          <th class="text-center">Transaktionen</th>
        </tr>
      </thead>
      <tbody>

        {% for c in sub_categories %}

        <tr>
          <td><input type="checkbox" class="form-input-styled"></td>

          <td>
            <ul class="list-unstyled mb-0">
              <li><span class="font-weight-semibold"> {{c.category.category_name}} -{{ c.sub_category_name }}</span></li>
            </ul>
          </td>
          <td class="text-center">
            <div class="list-icons">
              <div class="list-icons-item dropdown">
                <a href="gallery_library.html#" class="list-icons-item caret-0 dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-menu9"></i>
                </a>

                <div class="dropdown-menu dropdown-menu-right">
                  <a href="{% url 'category:update-subcategory' c.pk %}" class="dropdown-item"><i class="icon-pencil7"></i> Bearbeiten</a>
                  <div class="dropdown-divider"></div>
                  <a href="{% url 'category:delete-subcategory' c.pk %}" class="dropdown-item"><i class="icon-bin"></i> Löschen</a>
                </div>
              </div>
            </div>
          </td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>

</div>
<!-- /content area -->


{% include 'adminpanel/index/footer.html' %}

templates/adminpanel/category/add_list_sub_category_2.html
{% load static %}
{% include 'adminpanel/index/header.html' %}

<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/form_layouts.js' %}"></script>
<script src="{% static 'admin/js/plugins/media/fancybox.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/special/gallery_deneme.js' %}"></script>

{% include 'adminpanel/index/lefttopbar-ust.html' %}
{% include 'adminpanel/index/page-header.html' %}

<div class="content">

  {% if messages %}
    {% for message in messages %}
      {% ifequal message.tags 'error' %}
      <div class="alert alert-danger" role="alert">
        {{ message }}
      </div>
      {% else %}
      <div class="alert alert-{{ message.tags }}" role="alert">
        {{ message }}
      </div>
      {% endifequal %}
    {% endfor %}
  {% endif %}

      <div class="card">
        <div class="card-header header-elements-inline">
          <h5 class="card-title">Kategori Ekle/Listele</h5>
          <div class="header-elements">
            <div class="list-icons">
              <a class="list-icons-item" data-action="collapse"></a>
            </div>
          </div>
        </div>

        <div class="card-body">
          <form action="{% url 'category:add-list-subcategory2' %}" method="POST">
            {% csrf_token %}
                  <div class="form-group">
                    <label>Kategori :</label>
                    {{ form.sub_category2_name }}
                  </div>
                  <div class="form-group">
                    <label>TOP :</label>
                    {{ form.top_category }}
                  </div>
                  <div class="form-group">
                    <label>Kategori:</label>
                    <select name="sub_category_pk" data-placeholder="Kategori Seçiniz" class="form-control" >
                      <option value="">------</option>
                      {% for c in sub_categories %}
                        <option value="{{c.pk}}">{{ c.sub_category_name }}</option>
                      {% endfor %}
                    </select>
                  </div>

            <div class="text-right">
              <button type="submit" class="btn btn-primary"> Ekle <i class="icon-paperplane ml-2"></i></button>
            </div>
          </form>
        </div>
      </div>

    <div class="card">
    <div class="card-header bg-white header-elements-inline">
      <h4 class="card-title">Kategori</h4>
    </div>

    <table class="table table-striped media-library">
      <thead>
        <tr>
          <th><input type="checkbox" class="form-input-styled"></th>
          <th>Kategori</th>
          <th class="text-center">İşlem</th>
        </tr>
      </thead>
      <tbody>

        {% for c in sub_categories_2 %}
          <tr>
            <td><input type="checkbox" class="form-input-styled"></td>
            <td>
              <ul class="list-unstyled mb-0">
                <li><span class="font-weight-semibold">{{ c.sub_category2_name }}</span></li>
              </ul>
            </td>
            <td class="text-center">
              <div class="list-icons">
                <div class="list-icons-item dropdown">
                  <a href="gallery_library.html#" class="list-icons-item caret-0 dropdown-toggle" data-toggle="dropdown">
                    <i class="icon-menu9"></i>
                  </a>
                  <div class="dropdown-menu dropdown-menu-right">
                    <a href="{% url 'category:update-subcategory2' c.pk %}" class="dropdown-item"><i class="icon-pencil7"></i> Düzenle</a>
                    <div class="dropdown-divider"></div>
                    <a href="{% url 'category:delete-subcategory2' c.pk %}" class="dropdown-item"><i class="icon-bin"></i> Sil</a>
                  </div>
                </div>
              </div>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

</div>
<!-- /content area -->


{% include 'adminpanel/index/footer.html' %}

templates/adminpanel/category/update_category.html
{% load static %}
{% include 'adminpanel/index/header.html' %}

<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/form_layouts.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
<script src="{% static 'admin/js/plugins/uploaders/fileinput/plugins/purify.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/uploaders/fileinput/plugins/sortable.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/uploaders/fileinput/fileinput.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/uploader_bootstrap.js' %}"></script>

{% include 'adminpanel/index/lefttopbar-ust.html' %}
{% include 'adminpanel/index/page-header.html' %}

<!-- Content area -->
<div class="content">

  <!-- Vertical form options -->
  <div class="row">
    <div class="col-md-12">

      <!-- Basic layout-->
      <div class="card">
        <div class="card-header header-elements-inline">
          <h5 class="card-title">Kategorie Aktualisieren</h5>

        </div>

        <div class="card-body">
      <form action="{% url 'category:update-category' form.instance.pk %}" method="post">
        {% csrf_token %}

        <div class="form-group">
          <label>Kategorie:</label>
          {{ form.category_name }}
        </div>
        
        <div class="form-group">
        <label>TOP :</label>
        {{ form.top_category }}
        </div>

        <div class="text-right">
          <button type="submit" class="btn btn-primary">Informationen Aktualisieren <i class="icon-paperplane ml-2"></i></button>
        </div>

      </form>
      </div>
      </div>
    </div>
  </div>
</div>




{% include 'adminpanel/index/footer.html' %}