accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .view import superadmin, client, kullanici

app_name = 'accounts'

urlpatterns = [
    path('logout/', views.logout_view, name="logout"),
    path('login/', views.login_view, name="login"),

    path('client-register/', client.client_register, name="client-register"),
    path('client-password-change/', client.client_password_change, name="client-password-change"),

    path('kullanici-register/', kullanici.kullanici_register, name="kullanici-register"),
    path('kullanici-update/', kullanici.kullanici_update, name="kullanici-update"),
    path('kullanici-password-change/', kullanici.kullanici_password_change, name="kullanici-password-change"),


    path('superadmin-register/', superadmin.superadmin_register, name="superadmin-register"),
    path('superadmin-update/', superadmin.superadmin_update, name="superadmin-update"),
    path('superadmin-password-change/', superadmin.superadmin_password_change, name="superadmin-password-change"),

    path('client-delete/<slug:slug>/', superadmin.client_delete, name="client-delete"),
    path('add-client/', superadmin.add_client, name="add-client"),
    path('client-password-change-from-admin/<slug:slug>/', superadmin.client_password_change_from_admin, name="client-password-change-from-admin"),
    path('client-update/<slug:slug>/', superadmin.client_update, name="client-update"),

    path('add-kullanici/', superadmin.add_kullanici, name="add-kullanici"),
    path('kullanici-list/', superadmin.kullanici_list, name="kullanici-list"),
    path('kullanici-delete/<slug:slug>/', superadmin.kullanici_delete, name="kullanici-delete"),
    path('kullanici-update-from-admin/<slug:slug>/', superadmin.kullanici_update_from_admin, name="kullanici-update-from-admin"),
    
    path('kullanici-duty-delete/<int:pk>/', superadmin.kullanici_duty_delete, name="kullanici-duty-delete"),
    path('kullanici-duty-update/<int:pk>/', superadmin.kullanici_duty_update, name="kullanici-duty-update"),
    path('add-list-duty/', superadmin.add_list_duty, name="add-list-duty"),

]

order/urls.py
from django.urls import path
from .views import orders, siparis

app_name = 'order'

urlpatterns = [
    path('addtocart/<int:pk>/', orders.add_to_cart, name='addtocart'),
    path('delete-cartproduct/<int:pk>/', orders.delete_cart_product, name='delete-cartproduct'),
    path('updatecart/<int:pk>/', orders.update_cart, name='update-cart'),
    
    # path('odeme/', orders.orderproduct, name='checkout'),
    # path('sepet/', orders.cart_view, name="cart"),
    # path('stripe-odeme/', orders.stripe_view, name="stripe-odeme"),


    path('siparis-duzenle/<int:pk>/', siparis.siparis_duzenle_view, name="siparis-duzenle"),
    path('siparis-listele/', siparis.siparis_listele_view, name="siparis-listele"),
    path('siparis-sil/<int:pk>/', siparis.siparis_sil_view, name="siparis-sil"),
    
]

yagdukkanim/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('website.urls','website'),namespace='website')),
    path('adminpanel/', include(('adminpanel.urls','adminpanel'),namespace='adminpanel')),
    path('hesap/', include(('accounts.urls','accounts'), namespace='accounts')),
    path('satis/', include(('order.urls','order'), namespace='order')),
    path('kategori/', include(('category.urls','category'), namespace='category')),
    path('urun/', include(('product.urls','product'), namespace='product')),
    path('musteri/', include(('client.urls','client'), namespace='client')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth import authenticate
from .models import Superadmin, Kullanici, Duty, CompanyImage, CompanyInfo
from client.models import *
import re

class UserRegisterForm(UserCreationForm):

    email = forms.EmailField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email', 'type':'email'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Kullanıcı Adı'}))
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Adı'}))
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Soyadı'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Parola'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Parola Tekrar'}))

    class Meta:
        model = User
        fields=('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    def save(self, commit=True):
        user = super().save(commit=False)

        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()
        return user

class UserUpdateForm(UserChangeForm):
    first_name = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Vorname'}))
    last_name = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nachname'}))
    email = forms.EmailField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email', 'type':'email'}))
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nutzername'}))

    class Meta:
        model = User
        fields=('first_name','last_name','email', 'username', 'password')


class LoginForm(forms.ModelForm):
    username = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nutzername'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Passwort'}))
    #captcha = ReCaptchaField()

    class Meta:
        model = User
        fields = ('username','password')

    def clean(self):
        if self.is_valid():
            username = self.cleaned_data['username']
            password = self.cleaned_data['password']
            if not authenticate(username=username, password=password):
                raise forms.ValidationError('Hatalı Giriş')

class UserPasswordChangeForm(forms.Form):
    user = None
    old_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Altes Passwort'}))
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Neues Kennwort'}))
    new_password_again = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Wiederholen Sie das neue Passwort'}))

    def __init__(self, user, *args, **kwargs):
        self.user = user
        super(UserPasswordChangeForm, self).__init__(*args, **kwargs)

    def clean(self):
        new_password = self.cleaned_data.get('new_password')
        new_password_again = self.cleaned_data.get('new_password_again')

        if new_password != new_password_again:
            self.add_error('new_password', 'Yeni Şifreler Eşleşmedi')
            self.add_error('new_password_again', 'Yeni Şifreler Eşleşmedi')

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        if not self.user.check_password(old_password):
            raise forms.ValidationError('Lütfen Şifrenizi Giriniz')
        return old_password


class ClientCompanyForm(forms.ModelForm):
    vergi_dairesi = forms.CharField(max_length=250, required=False, widget=forms.TextInput(attrs={'class': 'form-control','id':'vergi_dairesi', 'placeholder': 'Steuerverwaltung' }))
    vergi_no = forms.CharField(max_length=250, required=False, widget=forms.TextInput(attrs={'class': 'form-control','id':'vergi_no', 'placeholder': 'Steuernummer'}))
    firma_unvani = forms.CharField(max_length=250, required=False, widget=forms.TextInput(attrs={'class': 'form-control','id':'firma_unvani', 'placeholder': 'Name der Firma'}))
    company_address = forms.CharField(max_length=250, required=False, widget=forms.TextInput(attrs={'class': 'form-control','id':'company_address', 'placeholder': 'Firmenanschrift'}))
    company_telephone =forms.CharField(max_length=250, required=False, widget=forms.TextInput(attrs={'class': 'form-control','id':'company_telephone', 'placeholder': 'Firmennummer'}))
    
    class Meta:
        model = ClientCompany
        fields = ('vergi_dairesi','vergi_no','firma_unvani', 'company_address','company_telephone')


class ClientRegisterForm(forms.ModelForm):
    tckn = forms.CharField(max_length=250, widget=forms.TextInput(attrs={'class': 'form-control','id':'tckn', 'placeholder': 'Müşteri TC Kimlik No', 'onkeypress':'if ( isNaN( String.fromCharCode(event.keyCode) )) return false;' , 'maxLength':11, 'oninput':'javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);'}))
    class Meta:
        model = Client
        fields = ('tckn',)

class SuperadminRegisterForm(forms.ModelForm):
    superadmin_duty = forms.CharField(max_length=250, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Mitarbeiterpflicht'}))
    class Meta:
        model = Superadmin
        fields = ('superadmin_duty',)

class DutyForm(forms.ModelForm):
    duty_name = forms.CharField(max_length=250, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Aufgabe'}))
    class Meta:
        model = Duty
        fields = ('duty_name',)

class KullaniciRegisterForm(forms.ModelForm):
    duty = forms.ModelChoiceField(queryset=Duty.objects.all(),widget=forms.Select(attrs={'class':'selectpicker', 'data-live-search':'true'}))
    class Meta:
        model = Kullanici
        fields = ('duty',)


class CompanyInfoForm(forms.ModelForm):
    company_address = forms.CharField(max_length=400, widget=forms.Textarea(attrs={'rows':5,'class': 'form-control', 'placeholder': 'Firmenanschrift'}))
    company_address_2 = forms.CharField(max_length=400, widget=forms.Textarea(attrs={'rows':5,'class': 'form-control', 'placeholder': 'Firmenanschrift - 2'}))
    company_phone_number = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Firmennummer'}))
    company_phone_number_2 = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Firmennummer - 2'}))
    company_mobile_phone_number = forms.CharField(max_length=60, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Handynummer des Unternehmens'}))
    company_mobile_phone_number_two = forms.CharField(max_length=60, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Handynummer des Unternehmens 2'}))
    company_email = forms.EmailField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email', 'type':'email'}))
    company_twitter = forms.CharField(max_length=60, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Twitter-Adresse des Unternehmens'}))
    company_instagram = forms.CharField(max_length=60, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Instagram-Adresse des Unternehmens'}))
    company_facebook = forms.CharField(max_length=60, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Facebook-Adresse des Unternehmens'}))
    company_youtube = forms.CharField(max_length=60, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Youtube'}))
    company_skype = forms.CharField(max_length=60, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Skype'}))
    company_pinterest = forms.CharField(max_length=60, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Pinterest'}))
    company_google = forms.CharField(max_length=60, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Google'}))
    company_flickr = forms.CharField(max_length=60, required=False, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Flickr'}))
    company_about_us = forms.CharField(max_length=400, widget=forms.Textarea(attrs={'rows':5,'class': 'form-control', 'placeholder': 'Firma über uns'}))

    class Meta:
        model = CompanyInfo
        fields = ('company_address', 'company_address_2','company_phone_number','company_phone_number_2', 'company_mobile_phone_number', 'company_mobile_phone_number_two', 'company_email', 'company_twitter', 'company_instagram', 'company_facebook','company_youtube','company_skype','company_pinterest','company_google','company_flickr', 'company_about_us')


class CompanyImageForm(forms.ModelForm):
    company_image = forms.ImageField(required=False,label='', widget=forms.ClearableFileInput(attrs={'class':'file-input'}))
    class Meta:
        model = CompanyImage
        fields = ('company_image',)

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from .forms import  LoginForm
from .models import CompanyInfo,CompanyImage

def get_auth(request):
    flag = False
    gidilecek_sayfa = ""
    if not request.user.is_authenticated:
        flag = True
        gidilecek_sayfa = 'accounts:login'
    try:
        musteri = request.user.client
        flag = True
        gidilecek_sayfa = 'website:index'
    except Exception as e:
        pass
    return flag, gidilecek_sayfa

def logout_view(request):
    logout(request)
    return redirect('accounts:login')

def login_view(request):
    print('fatih')
    if request.user.is_authenticated:
        try:
            superadmin = request.user.superadmin
            return redirect('adminpanel:index')
        except Exception as e:
            pass
        try:
            kullanici = request.user.kullanici
            return redirect('adminpanel:index')
        except Exception as e:
            pass
        try:
            musteri = request.user.client
            return redirect('website:index')
        except Exception as e:
            pass

    if request.POST:
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            print(username)
            print(password)

            user1 = authenticate(username=username, password=password)
            if user1:
                try:
                    superadmin = user1.superadmin
                    login(request, user1)
                    messages.success(request, 'Giriş İşlemi Başarılı')
                    return redirect('adminpanel:index')
                except Exception as e:
                    pass
                try:
                    kullanici = user1.kullanici
                    login(request, user1)
                    messages.success(request, 'Giriş İşlemi Başarılı')
                    return redirect('adminpanel:index')
                except Exception as e:
                    pass
                try:
                    client = user1.client
                    login(request, user1)
                    return redirect('musteri:musteri-ana-sayfa')
                except Exception as e:
                    pass
            else:
                messages.error(request, 'Giriş İşlemi Başarısız')
        else:
            messages.error(request, 'Giriş İşlemi Başarısız')
    else:
        login_form = LoginForm()
    try:
        company_info = CompanyInfo.objects.all()[0]
        company_image = CompanyImage.objects.all()[0]
    except Exception as e:
        company_info = ""
        company_image = ""
    context = {'login_form': login_form, 'company_info':company_info, 'company_image':company_image}
    return render(request, 'front_end/login/login.html', context)

templates/accounts/superadmin/add_list_duty.html
{% load static %}
{% include 'adminpanel/index/header.html' %}

<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/form_layouts.js' %}"></script>

<script src="{% static 'admin/js/plugins/media/fancybox.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/gallery_library.js' %}"></script>


{% include 'adminpanel/index/lefttopbar-ust.html' %}
{% include 'adminpanel/index/page-header.html' %}

<!-- Content area -->
<div class="content">

  {% if messages %}
  {% for message in messages %}
    {% ifequal message.tags 'error' %}
    <div class="alert alert-danger" role="alert">
      {{ message }}
    </div>
    {% else %}
    <div class="alert alert-{{ message.tags }}" role="alert">
      {{ message }}
    </div>
    {% endifequal %}

  {% endfor %}
  {% endif %}



      <div class="card">
        <div class="card-header header-elements-inline">
          <h5 class="card-title">Benutzeraufgabe hinzufügen</h5>
          <div class="header-elements">
            <div class="list-icons">
              <a class="list-icons-item" data-action="collapse"></a>
            </div>
          </div>
        </div>

        <div class="card-body">
          <form action="{% url 'accounts:add-list-duty' %}" method="POST">
            {% csrf_token %}
                  <div class="form-group">
                    <label>Benutzerposition:</label>
                    {{ form.duty_name }}
                  </div>

            <div class="text-right">
              <button type="submit" class="btn btn-primary">Ekle <i class="icon-paperplane ml-2"></i></button>
            </div>
          </form>
        </div>
      </div>



    <div class="card">
    <div class="card-header bg-white header-elements-inline">
      <h4 class="card-title">Benutzeraufgaben</h4>
    </div>

    <table class="table table-striped media-library">
      <thead>
        <tr>
          <th><input type="checkbox" class="form-input-styled"></th>

          <th>Aufgabe</th>
          <th class="text-center">Transaktionen</th>
        </tr>
      </thead>
      <tbody>

        {% for d in dutys %}

        <tr>
          <td><input type="checkbox" class="form-input-styled"></td>

          <td>
            <ul class="list-unstyled mb-0">
              <li><span class="font-weight-semibold">{{ d.duty_name }}</span></li>
            </ul>
          </td>
          <td class="text-center">
            <div class="list-icons">
              <div class="list-icons-item dropdown">
                <a href="gallery_library.html#" class="list-icons-item caret-0 dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-menu9"></i>
                </a>

                <div class="dropdown-menu dropdown-menu-right">
                  <a href="{% url 'accounts:kullanici-duty-update' d.pk %}" class="dropdown-item"><i class="icon-pencil7"></i> Bearbeiten</a>
                  <div class="dropdown-divider"></div>
                  <a href="{% url 'accounts:kullanici-duty-delete' d.pk %}" class="dropdown-item"><i class="icon-bin"></i> Löschen</a>
                </div>
              </div>
            </div>
          </td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>

</div>
<!-- /content area -->


{% include 'adminpanel/index/footer.html' %}

templates/accounts/superadmin/kullanici_list.html
{% load static %}
{% include 'adminpanel/index/header.html' %}

<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/form_layouts.js' %}"></script>

<script src="{% static 'admin/js/plugins/media/fancybox.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/gallery_library.js' %}"></script>

{% include 'adminpanel/index/lefttopbar-ust.html' %}
{% include 'adminpanel/index/page-header.html' %}

<!-- Content area -->
<div class="content">

  {% if messages %}
  {% for message in messages %}
    {% ifequal message.tags 'error' %}
    <div class="alert alert-danger" role="alert">
      {{ message }}
    </div>
    {% else %}
    <div class="alert alert-{{ message.tags }}" role="alert">
      {{ message }}
    </div>
    {% endifequal %}

  {% endfor %}
  {% endif %}
  <!-- Media library -->
  <div class="card">
    <div class="card-header bg-white header-elements-inline">
      <h4 class="card-title">Benutzer</h4>
    </div>

    <table class="table table-striped media-library">
      <thead>
        <tr>
          <th><input type="checkbox" class="form-input-styled"></th>
          <th>Vorname</th>
          <th>Nachname</th>
          <th>Email</th>
          <th>Nutzername</th>
          <th>Aufgabe</th>
          <th class="text-center">Transaktionen</th>
        </tr>
      </thead>
      <tbody>

        {% for k in kullanicilar %}

        <tr>
          <td><input type="checkbox" class="form-input-styled"></td>

          <td><a href="">{{ k.user.first_name }}</a></td>
          <td><a href="">{{ k.user.last_name }}</a></td>
          <td>
            <ul class="list-unstyled mb-0">
              <li><span class="font-weight-semibold">{{ k.user.email }}</span></li>
            </ul>
          </td>
          <td>
            <ul class="list-unstyled mb-0">
              <li><span class="font-weight-semibold">{{ k.user.username }}</span></li>
            </ul>
          </td>
          <td>
            <ul class="list-unstyled mb-0">
              <li><span class="font-weight-semibold">{{ k.duty.duty_name }}</span></li>
            </ul>
          </td>
          <td class="text-center">
            <div class="list-icons">
              <div class="list-icons-item dropdown">
                <a href="gallery_library.html#" class="list-icons-item caret-0 dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-menu9"></i>
                </a>

                <div class="dropdown-menu dropdown-menu-right">
                  <a href="{% url 'accounts:kullanici-update-from-admin' k.slug %}" class="dropdown-item"><i class="icon-pencil7"></i> Düzenle</a>
                  <div class="dropdown-divider"></div>
                  <a href="{% url 'accounts:kullanici-delete' k.slug %}" class="dropdown-item"><i class="icon-bin"></i> Sil</a>
                </div>
              </div>
            </div>
          </td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- /media library -->

</div>
<!-- /content area -->


{% include 'adminpanel/index/footer.html' %}

templates/accounts/superadmin/list_kullanici_duty.html
{% load static %}
{% include 'adminpanel/index/header.html' %}

<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/form_layouts.js' %}"></script>

<script src="{% static 'admin/js/plugins/media/fancybox.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/tables/datatables/datatables.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/gallery_library.js' %}"></script>

{% include 'adminpanel/index/lefttopbar-ust.html' %}
{% include 'adminpanel/index/page-header.html' %}

<!-- Content area -->
<div class="content">

  {% if messages %}
  {% for message in messages %}
    {% ifequal message.tags 'error' %}
    <div class="alert alert-danger" role="alert">
      {{ message }}
    </div>
    {% else %}
    <div class="alert alert-{{ message.tags }}" role="alert">
      {{ message }}
    </div>
    {% endifequal %}

  {% endfor %}
  {% endif %}

  <!-- Media library -->
  <div class="card">
    <div class="card-header bg-white header-elements-inline">
      <h4 class="card-title">Benutzer</h4>
    </div>

    <table class="table table-striped media-library">
      <thead>
        <tr>
          <th><input type="checkbox" class="form-input-styled"></th>
          <th>Aufgabe</th>
          <th class="text-center">Transaktionen</th>
        </tr>
      </thead>
      <tbody>

        {% for d in dutys %}

        <tr>
          <td><input type="checkbox" class="form-input-styled"></td>

          <td><a href="">{{ d.duty_name }}</a></td>

          <td class="text-center">
            <div class="list-icons">
              <div class="list-icons-item dropdown">
                <a href="gallery_library.html#" class="list-icons-item caret-0 dropdown-toggle" data-toggle="dropdown">
                  <i class="icon-menu9"></i>
                </a>

                <div class="dropdown-menu dropdown-menu-right">
                  <a href="{% url 'accounts:kullanici-duty-update' d.pk %}" class="dropdown-item"><i class="icon-pencil7"></i> Bearbeiten</a>
                  <div class="dropdown-divider"></div>
                  <a href="{% url 'accounts:kullanici-duty-delete' d.pk %}" class="dropdown-item"><i class="icon-bin"></i> Löschen</a>
                </div>
              </div>
            </div>
          </td>
        </tr>

        {% endfor %}
      </tbody>
    </table>
  </div>
  <!-- /media library -->

</div>
<!-- /content area -->


{% include 'adminpanel/index/footer.html' %}

templates/accounts/superadmin/superadmin_password_change.html
{% load static %}
{% include 'adminpanel/index/header.html' %}

<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/form_layouts.js' %}"></script>

{% include 'adminpanel/index/lefttopbar-ust.html' %}
{% include 'adminpanel/index/page-header.html' %}

<!-- Content area -->
<div class="content">

  {% if messages %}
  {% for message in messages %}
    {% ifequal message.tags 'error' %}
    <div class="alert alert-danger" role="alert">
      {{ message }}
    </div>
    {% else %}
    <div class="alert alert-{{ message.tags }}" role="alert">
      {{ message }}
    </div>
    {% endifequal %}

  {% endfor %}
  {% endif %}

  <!-- Vertical form options -->
  <div class="row">
    <div class="col-md-12">

      <!-- Basic layout-->
      <div class="card">
        <div class="card-header header-elements-inline">
          <h5 class="card-title">Benutzer hinzufügen</h5>

        </div>

        <div class="card-body">
      <form action="{% url 'accounts:superadmin-password-change' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
          <label>Altes Passwort:</label>
          {{ form.old_password }}
        </div>

        <label>Neues Kennwort:</label>
        <div class="form-group">
          {{ form.new_password }}
        </div>

        <div class="form-group">
          <label>Wiederhole das neue Passwort:</label>
          {{ form.new_password_again }}
        </div>

        <div class="text-right">
          <button type="submit" class="btn btn-primary">Passwort erneuern <i class="icon-paperplane ml-2"></i></button>
        </div>

      </form>
      </div>
      </div>
    </div>
  </div>
</div>


{% include 'adminpanel/index/footer.html' %}