accounts/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .view import superadmin, client, kullanici

app_name = 'accounts'

urlpatterns = [
    path('logout/', views.logout_view, name="logout"),
    path('login/', views.login_view, name="login"),

    path('client-register/', client.client_register, name="client-register"),
    path('client-password-change/', client.client_password_change, name="client-password-change"),

    path('kullanici-register/', kullanici.kullanici_register, name="kullanici-register"),
    path('kullanici-update/', kullanici.kullanici_update, name="kullanici-update"),
    path('kullanici-password-change/', kullanici.kullanici_password_change, name="kullanici-password-change"),


    path('superadmin-register/', superadmin.superadmin_register, name="superadmin-register"),
    path('superadmin-update/', superadmin.superadmin_update, name="superadmin-update"),
    path('superadmin-password-change/', superadmin.superadmin_password_change, name="superadmin-password-change"),

    path('client-delete/<slug:slug>/', superadmin.client_delete, name="client-delete"),
    path('add-client/', superadmin.add_client, name="add-client"),
    path('client-password-change-from-admin/<slug:slug>/', superadmin.client_password_change_from_admin, name="client-password-change-from-admin"),
    path('client-update/<slug:slug>/', superadmin.client_update, name="client-update"),

    path('add-kullanici/', superadmin.add_kullanici, name="add-kullanici"),
    path('kullanici-list/', superadmin.kullanici_list, name="kullanici-list"),
    path('kullanici-delete/<slug:slug>/', superadmin.kullanici_delete, name="kullanici-delete"),
    path('kullanici-update-from-admin/<slug:slug>/', superadmin.kullanici_update_from_admin, name="kullanici-update-from-admin"),
    
    path('kullanici-duty-delete/<int:pk>/', superadmin.kullanici_duty_delete, name="kullanici-duty-delete"),
    path('kullanici-duty-update/<int:pk>/', superadmin.kullanici_duty_update, name="kullanici-duty-update"),
    path('add-list-duty/', superadmin.add_list_duty, name="add-list-duty"),

]

adminpanel/urls.py
from django.urls import path
from . import views
from .view import blog, company, mesaj, slider , sss ,  footerimage, home_3, pages

app_name = 'adminpanel'

urlpatterns = [
    path('', views.index, name="index"),

    path('update-company-image/', company.update_company_image, name="update-company-image"),
    path('update-company-info/', company.update_company_info, name="update-company-info"),

    path('delete-mesaj/<int:pk>/', mesaj.delete_mesaj, name="delete-mesaj"),
    path('list-mesaj/', mesaj.list_mesaj, name="list-mesaj"),
    path('message-detail/<int:pk>/', mesaj.detail_mesaj, name="detail-mesaj"),
    path('add-mesaj/', mesaj.add_mesaj, name="add-mesaj"),
    path('update-sayfalar/', pages.update_sayfalar, name="update-sayfalar"),


    path('delete-sss/<int:pk>/', sss.delete_sss, name="delete-sss"),
    path('list-sss/', sss.list_sss, name="list-sss"),
    path('sss-detail/<int:pk>/', sss.detail_sss, name="detail-sss"),
    path('add-sss/', sss.add_sss, name="add-sss"),



    path('add-slider-images/', slider.add_slider_images, name="add-slider-images"),

    path('add-slider/', slider.add_slider, name="add-slider"),
    path('update-slider/<int:pk>/', slider.update_slider, name="update-slider"),
    path('detail-slider/<int:pk>/', slider.detail_slider, name="detail-slider"),
    path('delete-slider/<int:pk>/', slider.delete_slider, name="delete-slider"),
    path('list-slider/', slider.list_slider, name="list-slider"),
    path('update-slider-image/<int:pk>/', slider.update_slider_image, name="update-slider-image"),



    path('add-footer-images/', footerimage.add_footer_images, name="add-footer-images"),

    path('add-footer/', footerimage.add_footer, name="add-footer"),
    path('update-footer/<int:pk>/', footerimage.update_footer, name="update-footer"),
    path('detail-footer/<int:pk>/', footerimage.detail_footer, name="detail-footer"),
    path('delete-footer/<int:pk>/', footerimage.delete_footer, name="delete-footer"),
    path('list-footer/', footerimage.list_footer, name="list-footer"),
    path('update-footer-image/<int:pk>/', footerimage.update_footer_image, name="update-footer-image"),


    path('add-home-3/', home_3.add_home_3, name="add-home-3"),
    path('update-home-3/<int:pk>/', home_3.update_home_3, name="update-home-3"),
    path('detail-home-3/<int:pk>/', home_3.detail_home_3, name="detail-home-3"),
    path('delete-home-3/<int:pk>/', home_3.delete_home_3, name="delete-home-3"),
    path('list-home-3/', home_3.list_home_3, name="list-home-3"),
    path('update-home-3-image/<int:pk>/', home_3.update_home_3_image, name="update-home-3-image"),



    path('add-blog/', blog.add_blog, name="add-blog"),
    path('update-blog/<int:pk>/', blog.update_blog, name="update-blog"),
    path('detail-blog/<int:pk>/', blog.detail_blog, name="detail-blog"),
    path('delete-blog/<int:pk>/', blog.delete_blog, name="delete-blog"),
    path('list-blog/', blog.list_blog, name="list-blog"),
    path('update-blog-image/<int:pk>/', blog.update_blog_image, name="update-blog-image"),

]

order/urls.py
from django.urls import path
from .views import orders, siparis

app_name = 'order'

urlpatterns = [
    path('addtocart/<int:pk>/', orders.add_to_cart, name='addtocart'),
    path('delete-cartproduct/<int:pk>/', orders.delete_cart_product, name='delete-cartproduct'),
    path('updatecart/<int:pk>/', orders.update_cart, name='update-cart'),
    
    # path('odeme/', orders.orderproduct, name='checkout'),
    # path('sepet/', orders.cart_view, name="cart"),
    # path('stripe-odeme/', orders.stripe_view, name="stripe-odeme"),


    path('siparis-duzenle/<int:pk>/', siparis.siparis_duzenle_view, name="siparis-duzenle"),
    path('siparis-listele/', siparis.siparis_listele_view, name="siparis-listele"),
    path('siparis-sil/<int:pk>/', siparis.siparis_sil_view, name="siparis-sil"),
    
]

product/urls.py
from django.urls import path
from django.conf.urls import url
from .views import adminpanel_product , website_product, category, product_stock, brand, deserialize

app_name = 'product' 

urlpatterns = [

    path('add-product/', adminpanel_product.add_product_view, name="add-product"),
    path('list-product/', adminpanel_product.list_product_view, name="list-product"),
    path('update-product/<int:pk>/', adminpanel_product.update_product_view, name="update-product"),
    path('update-product-image/<int:pk>/', adminpanel_product.update_product_image, name="update-product-image"),
    path('delete-product/<int:pk>/', adminpanel_product.delete_product_view, name="delete-product"),
    path('list-delete-product-new/',adminpanel_product.list_product_new_view,name="list-delete-product"),


    path('add-product-stock/', product_stock.add_product_stock, name="add-product-stock"),
    path('list-product-stock/', product_stock.list_product_stock, name="list-product-stock"),
    path('update-product-stock/<int:pk>/', product_stock.update_product_stock, name="update-product-stock"),
    path('delete-product-stock/<int:pk>/', product_stock.delete_product_stock, name="delete-product-stock"),
    # path('deneme2/', product_stock.deneme, name="deneme2"),

    
    path('urunler/', website_product.all_products, name="all-products"),
    path('kategoriler/<slug:slug>/', website_product.category_filter_products, name="category-filter"),
    path('markalar/<slug:slug>/', website_product.brand_filter_products, name="brand-filter"),
    path('urun-detay/<slug:slug>/', website_product.product_detail, name="product-detail"),
    path('urun-popup-detail/<slug:slug>/', website_product.popup_product_detail, name="popup-product-detail"),
    path('yorum/<slug:slug>/', website_product.add_comment, name="add-comment"), 

    
    # path('brand/<slug:slug>/', website_product.brand_view, name="brand-filter"),
    # path('filter2/<slug:slug>/', website_product.top_category, name="filter2"),


    # path('sale/', website_product.sale_view, name="sale"),

    # path('suchergebnis/', website_product.search_view, name="arananurunler"),
    # url(r'^produktdetail/(?P<slug>[-\w]+)/$', website_product.product_detail, name="product-detail"),


    path('load-ending/', category.load_ending, name="load-ending"),
    path('load-categories/', category.load_categories, name="load-categories"),

    path('deneme/', deserialize.deneme, name="deneme"),
    # path('deserializer-category/', deserialize.deserializer_category, name="deserializer-category"),
    # path('deserializer-brand/', deserialize.deserializer_brand, name="deserializer-brand"),
    # path('deserializer-size/', deserialize.deserializer_size, name="deserializer-size"),
    # path('deserializer-color/', deserialize.deserializer_color, name="deserializer-color"),
    # path('deserializer/', deserialize.deserializer, name="deserializer"),
    # path('seperate-image/', deserialize.seperate_image, name="seperate-image"),
    # path('delete/', deserialize.delete, name="delete"),
    # path('same-delete/', deserialize.same_delete, name="same-delete"),



    path('add-brand/', brand.add_brand, name="add-brand"),
    path('update-brand/<int:pk>/', brand.update_brand, name="update-brand"),
    path('detail-brand/<int:pk>/', brand.detail_brand, name="detail-brand"),
    path('delete-brand/<int:pk>/', brand.delete_brand, name="delete-brand"),
    path('list-brand/', brand.list_brand, name="list-brand"),
    path('update-brand-image/<int:pk>/', brand.update_brand_image, name="update-brand-image"),



]



    # path('deserializer-category/', deserialize.deserializer_category, name="deserializer-category"),
    # path('deserializer-brand/', deserialize.deserializer_brand, name="deserializer-brand"),
    # path('deserializer-size/', deserialize.deserializer_size, name="deserializer-size"),
    # path('deserializer-color/', deserialize.deserializer_color, name="deserializer-color"),
    # path('deserializer/', deserialize.deserializer, name="deserializer"),
    # path('seperate-image/', deserialize.seperate_image, name="seperate-image"),
    # path('delete/', deserialize.delete, name="delete"),
    # path('same-delete/', deserialize.same_delete, name="same-delete"),

website/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

app_name = 'adminpanel'

urlpatterns = [
path('',views.home,name='home'),
path('hakkimizda/',views.about,name='about'),
path('iletisim/',views.contact,name='contact'),
path('urunler/',views.product,name='product'),
path('kategori/',views.category,name='category'),
path('giris/',views.login,name='login'),
path('kayit-ol/',views.register,name='register'),
path('favorilerim/',views.wishlist,name='wishlist'),
path('hesabım/',views.account,name='account'),
path('sepet/',views.cart,name='cart'),
path('odeme/',views.checkout,name='checkout'),
path('cerez-politikasi/',views.cookie_policy,name='cookie_policy'),
]

yagdukkanim/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('website.urls','website'),namespace='website')),
    path('adminpanel/', include(('adminpanel.urls','adminpanel'),namespace='adminpanel')),
    path('hesap/', include(('accounts.urls','accounts'), namespace='accounts')),
    path('satis/', include(('order.urls','order'), namespace='order')),
    path('kategori/', include(('category.urls','category'), namespace='category')),
    path('urun/', include(('product.urls','product'), namespace='product')),
    path('musteri/', include(('client.urls','client'), namespace='client')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/forms.py
from django import forms
from .models import Transfer
from accounts.models import Client
from django.contrib.auth.models import User


class UpdateClientForm(forms.ModelForm):
    tckn = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control', 'onkeypress':'if ( isNaN( String.fromCharCode(event.keyCode) )) return false;', 'maxLength':11, 'oninput':'javascript: if (this.value.length > this.maxLength) this.value = this.value.slice(0, this.maxLength);'}))
    class Meta:
        model = Client
        fields = ['tckn']

class UpdateUserInfoForm(forms.ModelForm):
    first_name = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control', 'type':'email'}))
    username = forms.CharField(max_length=60, widget=forms.TextInput(attrs={'class': 'form-control' ,'readonly':'true'}))
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'username']

product/views/brand.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from ..models import Brand , BrandImage
from ..forms import BrandForm , BrandImageForm , BrandUpdateFormForImage

def delete_brand(request,pk):
    brand = get_object_or_404(Brand, pk=pk)
    brand.delete()
    messages.success(request, 'Marka Silindi.')
    return redirect('product:list-brand')

def detail_brand(request, pk):
    brand = get_object_or_404(Brand, pk=pk)
    context = {'brand': brand, 'pageheader': 'Marka Detay'}
    return render(request, 'adminpanel/brand/detail_brand.html', context)

def list_brand(request):
    brands = Brand.objects.all()
    context = {'brands': brands, 'pageheader': 'Markalar'}
    return render(request, 'adminpanel/brand/list_brand.html', context)

def update_brand(request,pk):
    brand = get_object_or_404(Brand, pk=pk)
    form = BrandForm(instance=brand, data=request.POST or None)
    if request.POST:
        if form.is_valid():
            form.save()
            messages.success(request, 'Marka Güncelleme Başarılı.')
            return redirect('product:list-brand')
        else:
            messages.error(request, 'Marka Güncelleme Başarısız...!!')

    context = {'form': form, 'pageheader': 'Marka Güncelle'}
    return render(request, 'adminpanel/brand/update_brand.html', context)

def add_brand(request):
    if request.POST:
        form = BrandForm(request.POST)
        imageForm = BrandImageForm(request.POST, request.FILES)
        files = request.FILES.getlist('brand_image')

        if form.is_valid() :
            brand = form.save()
            if imageForm.is_valid() and files:
                numberOfPhotosToUpload = 8
                countOfPhotosUploaded = 0
                for f in files:
                    countOfPhotosUploaded +=1
                    uploadedPhoto = BrandImage(brand=brand,brand_image=f)
                    if countOfPhotosUploaded <= numberOfPhotosToUpload:
                        uploadedPhoto.save()

            messages.success(request, 'Marka Ekleme Başarılı.')
            return redirect('product:list-brand')
        
        else:
            messages.error(request, 'Marka Ekleme Başarısız...!!')
    else:
        form = BrandForm()
        imageForm = BrandImageForm(request.POST, request.FILES)

    context = {'form': form, 'pageheader': 'Marka Ekle', "imageForm":imageForm, }
    return render(request, 'adminpanel/brand/add_brand.html', context)


def update_brand_image(request, pk):
    brand = get_object_or_404(Brand, pk=pk)
    form = BrandUpdateFormForImage(instance=brand, data=request.POST or None)

    imageQuery = []
    for img in brand.get_brand_image():
        imageQuery.append(BrandImage.objects.get(pk=img.pk))
        BrandImage.objects.get(pk=img.pk).delete()

    image_sayisi = 8 - len(imageQuery)
    imageForm = BrandImageForm(data=request.POST or None, files=request.FILES or None)

    if request.POST:

        imageForm = BrandImageForm(data=request.POST,files=request.FILES)
        files = request.FILES.getlist('brand_image')
        if  form.is_valid() and imageForm.is_valid():
            brand = form.save()

            countOfPhotosUploaded = 0
            for f in files:
                countOfPhotosUploaded +=1
                uploadedPhoto = BrandImage(brand=brand,brand_image=f)
                if countOfPhotosUploaded <= image_sayisi:
                    uploadedPhoto.save()

            return redirect('product:list-brand')
        else:
            messages.error(request, 'Marka Logo Güncelleme Başarısız...!!')

        messages.success(request, 'Marka Logo Güncelleme Başarılı.')
        return redirect('product:list-brand')

    return render(request, 'adminpanel/brand/update_brand_image.html', context={'pageheader': 'Brand Foto Update','form':form, 'imageForm':imageForm })

product/views/category.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from category.models import Category, SubCategory, SubCategory2


def load_ending(request):

    category_pk = request.GET.get('category_pk')
    category = get_object_or_404(Category, pk = category_pk)

    sub_categories = SubCategory.objects.filter(category=category)
    print('****************')
    print(sub_categories)
    
    return render(request, 'adminpanel/product/load_ending.html', context={'sub_categories': sub_categories})

def load_categories(request):
    sub_category_pk = request.GET.get('sub_category_pk')
    sub_category = get_object_or_404(SubCategory, pk = sub_category_pk)

    sub_categories_2 = SubCategory2.objects.filter(sub_category=sub_category)

    return render(request, 'adminpanel/product/load_categories.html', context={'sub_categories_2': sub_categories_2})

templates/website/cart.html
{% load static %}
{% load i18n %}
{% include 'website/base/header.html' %}
<title> Modadivivere - {% trans "Warenkorb" %}</title>
</head>
<body class="style-10">
   <!-- LOADER -->
   <div id="loader-wrapper">
      <div class="bubbles">
         <div class="title">{% trans "Wird geladen" %}</div>
         <span></span>
         <span id="bubble2"></span>
         <span id="bubble3"></span>
      </div>
   </div>
   <div id="content-block">


   
   {% include 'website/base/header2.html' %}



   <div class="content-push">
   <div class="breadcrumb-box">
      <a href="{% url 'website:index' %}"> {% trans "Home" %}</a>
      <a href="{% url 'product:tumurunler' %}">{% trans "Produkte" %}</a>
      <a href="#">{% trans "Warenkorb" %} </a>
   </div>
   <div class="information-blocks">
      <div class="row">
         <div class="col-sm-9 col-md-9 information-entry">
            <h3 class="cart-column-title size-1"> {% trans "Warenkorb" %}</h3>
            {% for cp in shop_cart %}
            <div class="traditional-cart-entry style-1">
               {% if cp.product.product_pictures  %}
               <a class="image" href="{% url 'product:product-detail' cp.product.slug %}"><img alt="" src="/static/website/images/{{cp.product.product_coverpic}}" ></a>
               {% else %}
               <a class="image" href="{% url 'product:product-detail' cp.product.slug %}"><img alt="" src="{{cp.product.get_product_image.0.get_image_url}}" ></a>
               {% endif %}
               <div class="content">
                  <div class="cell-view">
                     <a class="tag" href="#">{{ cp.product.category }}</a>
                     <a class="title" href="{% url 'product:product-detail' cp.product.slug %}">{{ cp.product.product_name }} - {{ cp.size }}</a>
                     {% if cp.product.product_title %}
                     <div class="inline-description">{{ cp.product.product_title | safe }} </div>
                     {% endif %}
                     <div class="inline-description">{{ cp.product.product_detail | safe }}</div>
                     <div class="price">
                        {% if cp.product.product_sale == "Indirimli Urun" %}
                            <div class="prev"> {{cp.product.product_price }}</div>
                            <div class="current">CHF.  {{cp.product.product_price_sale }}</div>
                            <br>
                            <div class="prev"> {{cp.product.product_price2 }}</div>
                            <div class="current"> EUR. {{cp.product.product_price2_sale }}</div>
                        {% else %}
                        <div class="current"> CHF.  {{cp.product.product_price }}</div>
                        <div class="current"> EUR. {{cp.product.product_price2 }}</div>
                        {% endif %}
                     </div>
                     <div class="quantity-selector detail-info-entry">
                        <div class="detail-info-entry-title"> {% trans "Menge" %} : <span style="color:red; font-size:20px;"> {{ cp.quantity }} </span> </div>
                     </div>
                     <form action="{% url 'order:addtocart' cp.product.pk %}" method='POST'>
                        {% csrf_token %}
                        <div class="quantity buttons_added" >
                           <input name="quantity" style="height: 35px;" id="quantity" class="input" type="number" min="0" max="10"  value="1" /> &nbsp; <button type="submit" class="button style-15 add-to-cart"> {% trans "Hinzufügen" %}  </button>
                           <a href="{% url 'order:delete-cartproduct' cp.pk %}" class="button style-17" onclick="return confirm('Sind Sie sicher, dass Sie das Produkt löschen möchten?')" > {% trans "Löschen" %} </a>
                           <input name="size" id="size"  value="{{ cp.size }}" type="hidden" />
                        </div>
                     </form>
                  </div>
               </div>
            </div>
            {% endfor %}
            <div class="information-blocks">
               <div class="row">
                  <div class="information-entry col-md-6">
                     <div class="sale-entry sale-entry-border" style="background: #333;">
                        <div class="sale-price"><img src="{% static 'website/img/shipping-icon.png' %}" alt="" /></div>
                        <div class="sale-title">
                           <h3 style="font-family: none;">{% trans "100€ + Kostenloser Versand" %}  </h3>
                        </div>
                        <div class="sale-description"style="font-family: none;">
                           {% trans "Kostenloser Versand für Einkäufe von 100 € oder mehr über Moda Di Vivere." %}
                        </div>
                     </div>
                  </div>
                  <div class="information-entry col-md-6">
                     <div class="sale-entry sale-entry-border" style="background: #901794;">
                        <div class="sale-price"><img src="{% static 'website/img/shipping-icon.png' %}" alt="" /></div>
                        <div class="sale-title">
                           <h3 style="font-family: none;">{% trans "SCHNELL UND ZUVERLÄSSIG" %} </h3>
                        </div>
                        <div class="sale-description">{% trans "Mit der Zusicherung von Moda Di Vivere werden Ihre Produkte in kurzer Zeit vorbereitet und versendet." %} </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div class="col-sm-3 col-md-3 information-entry">
            <div class="sidebar-subtotal">
               <div class="price-data ;" >
                  <h3 class="cart-column-title size-1" style="text-align: center; border:none; margin-bottom:0px;">  {% trans "Warenkorb" %} ( {% if request.session.cart_items %}{{request.session.cart_items}} {% else %} 0 {% endif %}  {% trans "Artikel" %})  </h3>
                  <h3 class="cart-column-title size-1" style="text-align: center; border-bottom:none;">
                    {% trans "Gesamtbetrag" %}
                    <div class="main">CHF. {{total}}</div>
                  </h3>
                  <h3 class="cart-column-title size-1" style="text-align: center; border-bottom:none;">
                    {% trans "Gesamtbetrag" %}
                    <div class="main">EUR. {{total2}}</div>
                  </h3>
               </div>
               <div class="additional-data">
                  <form action="{% url 'order:checkout' %}" method='POST'>
                     {% csrf_token %}
                     <button type="submit" class="button style-10"> {% trans "Zahlungen" %} </button>
                  </form>
               </div>
            </div>
         </div>
      </div>
   </div>
   {% include 'website/base/footer.html' %}

templates/website/client_register.html
{% load static %}
{% include 'website/base/header.html' %}

  	<title>Modadivivere - Kundenregister</title>
</head>
<body class="style-10">

    <!-- LOADER -->
    <div id="loader-wrapper">
        <div class="bubbles">
            <div class="title">Wird geladen</div>
            <span></span>
            <span id="bubble2"></span>
            <span id="bubble3"></span>
        </div>
    </div>

    <div id="content-block">
{% include 'website/base/header2.html' %}

        <div class="content-center fixed-header-margin">


            <div class="content-push">

                <div class="breadcrumb-box">
                    <a href="{% url 'website:index' %}">Home</a>
                    <a href="#">Login Form</a>
                </div>

                <div class="information-blocks">
                    <div class="row">
                        <div class="col-sm-6 information-entry">
                            <div class="login-box">
                                <div class="article-container style-1">
                                    <h3>Anmelden</h3>
                                    <p>Modadivivere füllen Sie die folgenden Informationen aus, um Mitglied unserer Website zu werden.</p>
                                </div>
                                <form action="{% url 'accounts:client-register' %}" method="post">
                                    {% csrf_token %}
                                    <label>Name</label>
                                    {{ form.first_name }}
                                    <label>Nachname</label>
                                    {{ form.last_name }}
                                    <label>E Posta</label>
                                    {{ form.email }}
                                    <label>Benutzername</label>
                                    {{ form.username }}
                                    <label>TC Kennnummer</label>
                                    {{ client_form.tckn }}
                                    <label>Parola</label>
                                    {{ form.password1 }}
                                    <label>Passwort Erneut</label>
                                    {{ form.password2 }}
                                    <label></label>
                                    <div class="button style-10">Login Page<input type="submit" value="" /></div>
                                </form>
                            </div>
                        </div>
                        <div class="col-sm-6 information-entry">
                            <div class="login-box">
                                <div class="article-container style-1">
                                    <h3>Wenn Sie Mitglied Sind Anmelden</h3>
                                    <p>Modadivivere wenn Sie bereits Mitglied unserer Website sind,Anmelden.</p>
                                </div>
                                <a href="{% url 'accounts:login' %}" class="button style-12">Anmelden</a>
                            </div>
                        </div>
                    </div>
                </div>

{% include 'website/base/footer.html' %}

templates/website/index.html
{% load static %}
{% load i18n %}

{% include 'website/base/header.html' %}
  	<title> Modadivivere </title>

<link rel="stylesheet" href="{% static 'website/css/purecookie.css' %}"/>
<script src="{% static 'website/js/purecookie.js' %}"></script>

</head>
<body class="style-10">

    <!-- LOADER -->
    <div id="loader-wrapper">
        <div class="bubbles">
            <div class="title">{% trans "Wird geladen" %}</div>
            <span></span>
            <span id="bubble2"></span>
            <span id="bubble3"></span>
        </div>
    </div>

    <div id="content-block">

{% include 'website/base/header2.html' %}

            <div class="content-push">
               
{% include 'website/base/anasayfa_slider_full_width.html' %} 
{% include 'website/base/anasayfa_3lu_kategoriler.html' %} 
{% include 'website/product/featured-popular-new.html' %} 
{% include 'website/base/man_woman.html' %} 
{% include 'website/base/top_categories.html' %} 
{% include 'website/base/galery.html' %} 

{% include 'website/base/footer.html' %}

templates/website/login.html
{% load static %}
{% include 'website/base/header.html' %}

  	<title>Modadivivere - Anmeldung</title>
</head>
<body class="style-10">

    <!-- LOADER -->
    <div id="loader-wrapper">
        <div class="bubbles">
            <div class="title">Wird geladen</div>
            <span></span>
            <span id="bubble2"></span>
            <span id="bubble3"></span>
        </div>
    </div>

    <div id="content-block">
{% include 'website/base/header2.html' %}

        <div class="content-center fixed-header-margin">


            <div class="content-push">

                <div class="breadcrumb-box">
                    <a href="{% url 'website:index' %}">Home</a>
                    <a href="#">Anmelden</a>
                </div>

                <div class="information-blocks">
                    <div class="row">
                        <div class="col-sm-6 information-entry">
                            <div class="login-box">
                                <div class="article-container style-1">
                                    <h3> wenn Sie Mitglied sind Anmelden</h3>
                                    <p>Modadiviverewenn Sie bereits Mitglied unserer Website sind, sofort Anmelden .</p>
                                </div>
                                <form action="{% url 'accounts:login' %}" method="post">
                                {% csrf_token %}
                                    <label>Kullanıcı Adı</label>
                                    {{ login_form.username }}
                                    <label>Parola</label>
                                    {{ login_form.password }}

                                    <div class="button style-10">Anmelden<input type="submit" value="" /></div>
                                </form>
                            </div>
                        </div>
                        <div class="col-sm-6 information-entry">
                            <div class="login-box">
                                <div class="article-container style-1">
                                    <h3>Anmelden</h3>
                                    <p>Modadivivere erstellen Sie den folgenden sofortigen Benutzer, um Mitglied unserer Website zu werden.</p>
                                </div>
                                <a href="{% url 'accounts:client-register' %}" class="button style-12">Benutzer Erstellen</a>
                            </div>
                        </div>
                    </div>
                </div>

                

{% include 'website/product/special_products_2.html' %}

{% include 'website/base/footer.html' %}