adminpanel/urls.py
from django.urls import path
from . import views
from .view import blog, company, mesaj, slider , sss ,  footerimage, home_3, pages

app_name = 'adminpanel'

urlpatterns = [
    path('', views.index, name="index"),

    path('update-company-image/', company.update_company_image, name="update-company-image"),
    path('update-company-info/', company.update_company_info, name="update-company-info"),

    path('delete-mesaj/<int:pk>/', mesaj.delete_mesaj, name="delete-mesaj"),
    path('list-mesaj/', mesaj.list_mesaj, name="list-mesaj"),
    path('message-detail/<int:pk>/', mesaj.detail_mesaj, name="detail-mesaj"),
    path('add-mesaj/', mesaj.add_mesaj, name="add-mesaj"),
    path('update-sayfalar/', pages.update_sayfalar, name="update-sayfalar"),


    path('delete-sss/<int:pk>/', sss.delete_sss, name="delete-sss"),
    path('list-sss/', sss.list_sss, name="list-sss"),
    path('sss-detail/<int:pk>/', sss.detail_sss, name="detail-sss"),
    path('add-sss/', sss.add_sss, name="add-sss"),



    path('add-slider-images/', slider.add_slider_images, name="add-slider-images"),

    path('add-slider/', slider.add_slider, name="add-slider"),
    path('update-slider/<int:pk>/', slider.update_slider, name="update-slider"),
    path('detail-slider/<int:pk>/', slider.detail_slider, name="detail-slider"),
    path('delete-slider/<int:pk>/', slider.delete_slider, name="delete-slider"),
    path('list-slider/', slider.list_slider, name="list-slider"),
    path('update-slider-image/<int:pk>/', slider.update_slider_image, name="update-slider-image"),



    path('add-footer-images/', footerimage.add_footer_images, name="add-footer-images"),

    path('add-footer/', footerimage.add_footer, name="add-footer"),
    path('update-footer/<int:pk>/', footerimage.update_footer, name="update-footer"),
    path('detail-footer/<int:pk>/', footerimage.detail_footer, name="detail-footer"),
    path('delete-footer/<int:pk>/', footerimage.delete_footer, name="delete-footer"),
    path('list-footer/', footerimage.list_footer, name="list-footer"),
    path('update-footer-image/<int:pk>/', footerimage.update_footer_image, name="update-footer-image"),


    path('add-home-3/', home_3.add_home_3, name="add-home-3"),
    path('update-home-3/<int:pk>/', home_3.update_home_3, name="update-home-3"),
    path('detail-home-3/<int:pk>/', home_3.detail_home_3, name="detail-home-3"),
    path('delete-home-3/<int:pk>/', home_3.delete_home_3, name="delete-home-3"),
    path('list-home-3/', home_3.list_home_3, name="list-home-3"),
    path('update-home-3-image/<int:pk>/', home_3.update_home_3_image, name="update-home-3-image"),



    path('add-blog/', blog.add_blog, name="add-blog"),
    path('update-blog/<int:pk>/', blog.update_blog, name="update-blog"),
    path('detail-blog/<int:pk>/', blog.detail_blog, name="detail-blog"),
    path('delete-blog/<int:pk>/', blog.delete_blog, name="delete-blog"),
    path('list-blog/', blog.list_blog, name="list-blog"),
    path('update-blog-image/<int:pk>/', blog.update_blog_image, name="update-blog-image"),

]

order/urls.py
from django.urls import path
from .views import orders, siparis

app_name = 'order'

urlpatterns = [
    path('addtocart/<int:pk>/', orders.add_to_cart, name='addtocart'),
    path('delete-cartproduct/<int:pk>/', orders.delete_cart_product, name='delete-cartproduct'),
    path('updatecart/<int:pk>/', orders.update_cart, name='update-cart'),
    
    # path('odeme/', orders.orderproduct, name='checkout'),
    # path('sepet/', orders.cart_view, name="cart"),
    # path('stripe-odeme/', orders.stripe_view, name="stripe-odeme"),


    path('siparis-duzenle/<int:pk>/', siparis.siparis_duzenle_view, name="siparis-duzenle"),
    path('siparis-listele/', siparis.siparis_listele_view, name="siparis-listele"),
    path('siparis-sil/<int:pk>/', siparis.siparis_sil_view, name="siparis-sil"),
    
]

yagdukkanim/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('website.urls','website'),namespace='website')),
    path('adminpanel/', include(('adminpanel.urls','adminpanel'),namespace='adminpanel')),
    path('hesap/', include(('accounts.urls','accounts'), namespace='accounts')),
    path('satis/', include(('order.urls','order'), namespace='order')),
    path('kategori/', include(('category.urls','category'), namespace='category')),
    path('urun/', include(('product.urls','product'), namespace='product')),
    path('musteri/', include(('client.urls','client'), namespace='client')),

]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adminpanel/forms.py
from ckeditor.widgets import CKEditorWidget
from django import forms
from .models import Slider, Blog, SliderImage, BlogImage , SSS , FooterImage, Footer, Home3, Home3Image, Sayfalar

class BlogForm(forms.ModelForm):
    context = forms.CharField(required=False,widget=CKEditorWidget)
    def __init__(self, *args, **kwargs):
        super(BlogForm,self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs={'class':'form-control'}
        self.fields['context'].widget.attrs={'rows':10}
    class Meta:
        model = Blog
        fields = '__all__'

class BlogUpdateFormForImage(forms.ModelForm):
    title = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Blog Titel'}))
    class Meta:
        model = Blog
        fields = ('title',)

class BlogImageForm(forms.ModelForm):
    blog_image = forms.ImageField(required=False,label='', widget=forms.ClearableFileInput(attrs={'multiple':'multiple', 'class':'file-input', 'data-fouc':True}))
    class Meta:
        model = BlogImage
        fields = ('blog_image',)


class SliderForm(forms.ModelForm):
    context = forms.CharField(required=False, widget=CKEditorWidget)
    link = forms.CharField(required=False,max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Slider Verknüpfung'}))

    def __init__(self, *args, **kwargs):
        super(SliderForm,self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs={'class':'form-control'}
        self.fields['context'].widget.attrs={'rows':10}
    class Meta:
        model = Slider
        fields = '__all__'

class SliderUpdateFormForImage(forms.ModelForm):
    title = forms.CharField(required=False, max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Slider-Header'}))
    link = forms.CharField(required=False,max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Slider Verknüpfung'}))

    class Meta:
        model = Slider
        fields = ('title','link')

class SliderImageForm(forms.ModelForm):
    slider_image = forms.ImageField(required=False, label='', widget=forms.ClearableFileInput(attrs={'multiple':'multiple', 'class':'file-input', 'data-fouc':True ,'placeholder': 'Schieberegler Foto'}))
    class Meta:
        model = SliderImage
        fields = ('slider_image',)

class SSSForm(forms.ModelForm):
    sss_title = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Frage'}))
    sss_detail = forms.CharField(widget=CKEditorWidget)
    sss_id = forms.IntegerField(widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'ID für die Sequenzierung'}))

    def __init__(self, *args, **kwargs):
        super(SSSForm,self).__init__(*args, **kwargs)
        self.fields['sss_detail'].widget.attrs={'rows':10}

    class Meta:
        model = SSS
        fields = ['sss_id','sss_title','sss_detail']

"""
class AddCommentsForm(forms.ModelForm):
    senders_name = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Ad Soyad'}))
    senders_mail = forms.CharField(max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'E Posta'}))
    text = forms.CharField(max_length=750, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Yorum'}))
    
    class Meta:
        model = InstructorComments
        fields = ('senders_name','senders_mail','text')
"""



class FooterForm(forms.ModelForm):
    title = forms.CharField(required=False, max_length=250, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Footer-Header'}))
    link = forms.CharField(required=False,max_length=750, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Footer Verknüpfung'}))


    class Meta:
        model = Footer
        fields = '__all__'

class FooterUpdateFormForImage(forms.ModelForm):
    title = forms.CharField(required=False, max_length=250, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Footer-Header'}))
    link = forms.CharField(required=False,max_length=750, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Footer Verknüpfung'}))

    class Meta:
        model = Footer
        fields = ('title','link')

class FooterImageForm(forms.ModelForm):
    footer_image = forms.ImageField(required=False, label='', widget=forms.ClearableFileInput(attrs={'multiple':'multiple', 'class':'file-input', 'data-fouc':True ,'placeholder': 'Footer Foto'}))
    class Meta:
        model = FooterImage
        fields = ('footer_image',)


class Home3Form(forms.ModelForm):
    context = forms.CharField(required=False,widget=CKEditorWidget)
    def __init__(self, *args, **kwargs):
        super(Home3Form,self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs={'class':'form-control'}
        self.fields['context'].widget.attrs={'rows':10}
    class Meta:
        model = Home3
        fields = '__all__'

class Home3UpdateFormForImage(forms.ModelForm):
    title = forms.CharField(required=False, max_length=150, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Home3 Titel'}))
    class Meta:
        model = Home3
        fields = ('title',)

class Home3ImageForm(forms.ModelForm):
    home_3_image = forms.ImageField(required=False,label='', widget=forms.ClearableFileInput(attrs={'multiple':'multiple', 'class':'file-input', 'data-fouc':True}))
    class Meta:
        model = Home3Image
        fields = ('home_3_image',)



class SayfalarForm(forms.ModelForm):
    zollfrei_shopping   = forms.CharField(required=False,widget=CKEditorWidget)
    zhlungsmethoden     = forms.CharField(required=False,widget=CKEditorWidget)
    agbs                = forms.CharField(required=False,widget=CKEditorWidget)
    impressum           = forms.CharField(required=False,widget=CKEditorWidget)
    datenschutzerklarung = forms.CharField(required=False,widget=CKEditorWidget)
    class Meta:
        model = Sayfalar
        fields = '__all__'

adminpanel/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from accounts.views import get_auth
from .models import  Mesajlar
from django.contrib.auth import authenticate
from django.contrib.auth import update_session_auth_hash


def index(request):
    """
    flag, gidilecek_sayfa = get_auth(request)
    if flag:
        return redirect(gidilecek_sayfa)
    """

    mesajlar =Mesajlar.objects.all()



    context = { 'mesajlar':mesajlar }
    return render(request,'adminpanel/index/index.html', context)

templates/adminpanel/sss/add_sss.html
{% load static %}
{% include 'adminpanel/index/header.html' %}


<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/form_layouts.js' %}"></script>

<script src="{% static 'admin/js/plugins/uploaders/fileinput/plugins/purify.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/uploaders/fileinput/plugins/sortable.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/uploaders/fileinput/fileinput.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/uploader_bootstrap.js' %}"></script>




{% include 'adminpanel/index/lefttopbar-ust.html' %}
{% include 'adminpanel/index/page-header.html' %}




<!-- Content area -->
<div class="content">
  {% if messages %}
  {% for message in messages %}
    {% ifequal message.tags 'error' %}
    <div class="alert alert-danger" role="alert">
      {{ message }}
    </div>
    {% else %}
    <div class="alert alert-{{ message.tags }}" role="alert">
      {{ message }}
    </div>
    {% endifequal %}

  {% endfor %}
  {% endif %}
  <!-- Vertical form options -->
  <div class="row">
    <div class="col-md-12">

      <!-- Basic layout-->
      <div class="card">
        <div class="card-header header-elements-inline">
          <h5 class="card-title">SSS Hinzufügen</h5>

        </div>

        <div class="card-body">
          <form action="{% url 'adminpanel:add-sss' %}"  method="POST">
            {% csrf_token %}

            <div class="form-group">
            

                <div  style=" width: 45%; ">
                  {{ form.media }} 
                    {% for field in form %}
                      <div class="form-group">
                        {{field}}
                      </div>
                    {% endfor %}
                </div>
            </div>

            <div class="text-right">
              <button type="submit" class="btn btn-primary">SSS Veröffentlichen <i class="icon-paperplane ml-2"></i></button>
            </div>

          </form>

        </div>
      </div>
      <!-- /basic layout -->

    </div>
  </div>
</div>




{% include 'adminpanel/index/footer.html' %}

templates/adminpanel/sss/list_sss.html
{% load static %} {% include 'adminpanel/index/header.html' %}

<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/form_layouts.js' %}"></script>

<script src="{% static 'admin/js/plugins/media/fancybox.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/tables/datatables/datatables.min.js' %}"></script>

<script src="{% static 'admin/js/demo_pages/special/gallery_deneme.js' %}"></script>

{% include 'adminpanel/index/lefttopbar-ust.html' %} {% include 'adminpanel/index/page-header.html' %}

<!-- Content area -->
<div class="content">
    {% if messages %} {% for message in messages %} {% ifequal message.tags 'error' %}
    <div class="alert alert-danger" role="alert">
        {{ message }}
    </div>
    {% else %}
    <div class="alert alert-{{ message.tags }}" role="alert">
        {{ message }}
    </div>
    {% endifequal %} {% endfor %} {% endif %}
    <!-- Media library -->
    <div class="card">
        <div class="card-header bg-white header-elements-inline">
            <h4 class="card-title">Nachrichten</h4>
            <a style="background-color:yellow;" href="{% url 'adminpanel:add-sss' %}" class="nav-link">SSS Ekle </a>

        </div>

        <table class="table table-striped media-library">
            <thead>
                <tr>
                    <th><input type="checkbox" class="form-input-styled"></th>
                    <th>Başlık</th>

                    <th class="text-center">Transaktionen</th>
                </tr>
            </thead>
            <tbody>

                {% for p in sss %}
                <tr>
                    <td><input type="checkbox" class="form-input-styled"></td>

                    <td>{{ p.sss_title }}</td>



                    <td class="text-center">
                        <div class="list-icons">
                            <div class="list-icons-item dropdown">
                                <a href="gallery_library.html#" class="list-icons-item caret-0 dropdown-toggle" data-toggle="dropdown">
                                    <i class="icon-menu9"></i>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right">
                                    <a href="{% url 'adminpanel:detail-sss' p.pk %}" class="dropdown-item"><i class="icon-pencil7"></i> SSS Bearbeiten </a>
                                    <div class="dropdown-divider"></div>
                                    <a href="{% url 'adminpanel:delete-sss' p.pk %}" class="dropdown-item"><i class="icon-bin"></i>Löschen</a>
                                </div>
                            </div>
                        </div>
                    </td>
                </tr>


                {% endfor %}
            </tbody>
        </table>
    </div>
    <!-- /media library -->

</div>
<!-- /content area -->


{% include 'adminpanel/index/footer.html' %}

templates/adminpanel/sss/sss_detail.html
{% load static %}
{% include 'adminpanel/index/header.html' %}

<script src="{% static 'admin/js/plugins/forms/selects/select2.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/forms/styling/uniform.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/form_layouts.js' %}"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/js/bootstrap-select.min.js"></script>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.1/css/bootstrap-select.css" />
<script src="{% static 'admin/js/plugins/uploaders/fileinput/plugins/purify.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/uploaders/fileinput/plugins/sortable.min.js' %}"></script>
<script src="{% static 'admin/js/plugins/uploaders/fileinput/fileinput.min.js' %}"></script>
<script src="{% static 'admin/js/demo_pages/uploader_bootstrap.js' %}"></script>

{% include 'adminpanel/index/lefttopbar-ust.html' %}
{% include 'adminpanel/index/page-header.html' %}

<!-- Content area -->
<div class="content">

  <!-- Vertical form options -->
  <div class="row">
    <div class="col-md-12">

      <!-- Basic layout-->
      <div class="card">
        <div class="card-header header-elements-inline">
          <h3 class="card-title"><u>SSS Detail</u></h3>

        </div>
        <div class="card-body">
          <form action="{% url 'adminpanel:detail-sss' form.instance.pk %}"  method="POST">
            {% csrf_token %}
          <div class="form-group">

            <div class="form-group">
              {{ form.media }} 
                {% for field in form %}
                  <div class="form-group">
                    <label>{{field.label}}</label><br>
                    {{field}}
                  </div>
                {% endfor %}
            </div>

            <div class="text-right">
              <button type="submit" class="btn btn-primary">SSS Aktualisieren<i class="icon-paperplane ml-2"></i></button>
            </div>
          </div>
          </form>

        </div>
      </div>
    </div>
  </div>
</div>




{% include 'adminpanel/index/footer.html' %}